# Window settings
[window]
startup_mode = "Maximized"  # Start Alacritty in fullscreen mode
opacity = 0.80
decorations = "full"
dynamic_title = true


# Font settings
[font]
size = 14
#normal = { family = "Fira Code", style = "Medium" }  # Set font family and style

# Cursor settings
[cursor]
style = "Beam"              # Cursor shape: "Block", "Underline", or "Beam"
blink_interval = 500        # Cursor blink interval in milliseconds

# Scrolling
[scrolling]
history = 10000             # Number of lines in the scrollback buffer
multiplier = 3              # Scroll speed multiplier

[window.padding]
x = 8
y = 8

# ~/.config/alacritty/alacritty.toml

[colors.primary]
background = "0x101010"
foreground = "0xd3d3d3"

[colors.cursor]
text = "0x330000"
cursor = "0x555555"

[colors.normal]
black = "0x000000"
red = "0xff5555"
green = "0x44ee22"
yellow = "0xffff55"
blue = "0x00bbff"
magenta = "0xff55ff"
cyan = "0x00eeee"
white = "0xd3d3d3"

[colors.bright]
black = "0x333333"
red = "0xff6666"
green = "0x33ff99"
yellow = "0xffff99"
blue = "0x66ccff"
magenta = "0xff99ff"
cyan = "0x99ffff"
white = "0xffffff"

[colors.selection]
text = "0x000000"
background = "0x00ff66"

